apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: game-library-infra
type: Opaque
data:
  # echo -n "<mongo-root-username>" | base64
  mongo-root-username: ""
  # echo -n "<mongo-root-password>" | base64
  mongo-root-password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: graylog-secret
  namespace: game-library-infra
type: Opaque
data:
  # Used for encryption/salting. Must be at least 16 characters.
  # echo -n "$(openssl rand -hex 48)" | base64
  graylog-password-secret: ""
  # SHA256 hash of the desired admin password.
  # echo -n "$(echo -n "<password>" | sha256sum | cut -d " " -f1)" | base64
  graylog-root-password-sha2: ""
  # MongoDB connection URI. Must match credentials from mongo-secret.
  # echo -n "mongodb://<username>:<password>@mongo:27017/graylog?authSource=admin" | base64
  graylog-mongodb-uri: ""
