name: "deploy infra"

on:
  push:
    branches: [main]
    paths: [".k8s/**"]
  workflow_dispatch:

concurrency:
  group: deploy-infra
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Set context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CLUSTER_CONFIG }}

      - name: Replace variables
        run: |
          sed -i'' \
          -e 's/_DOMAIN_/${{ vars.DOMAIN }}/g' \
          -e 's/_ACME_EMAIL_/${{ secrets.ACME_EMAIL }}/g' \
          .k8s/*.yaml

      - name: Diff changes
        run: |
          kubectl diff -f .k8s/namespace.yaml || true
          kubectl diff -f .k8s/zipkin.yaml || true
          kubectl diff -f .k8s/prometheus.yaml || true
          kubectl diff -f .k8s/jaeger.yaml || true
          kubectl diff -f .k8s/mongo.yaml || true
          kubectl diff -f .k8s/opensearch.yaml || true
          kubectl diff -f .k8s/graylog.yaml || true
          kubectl diff -f .k8s/grafana.yaml || true
          kubectl diff -f .k8s/cert.yaml || true

      - name: Apply manifests
        run: |
          kubectl apply -f .k8s/namespace.yaml
          kubectl apply -f .k8s/zipkin.yaml
          kubectl apply -f .k8s/prometheus.yaml
          kubectl apply -f .k8s/jaeger.yaml
          kubectl apply -f .k8s/mongo.yaml
          kubectl apply -f .k8s/opensearch.yaml
          kubectl apply -f .k8s/graylog.yaml
          kubectl apply -f .k8s/grafana.yaml
          kubectl apply -f .k8s/cert.yaml
